/**
 * Selector Registry — Single source of truth for all E2E test selectors.
 *
 * RULES:
 * 1. ALL tests MUST import selectors from this file.
 * 2. NEVER hardcode selectors in test files.
 * 3. Frontend components MUST include matching data-testid (or configured convention) attributes.
 * 4. See ui-contracts.md for the full contract of required test hooks.
 *
 * This file is generated by /speckit.e2e.init and customized for the detected stack.
 * Add new selectors here as you add new gate tests.
 */

import { readFileSync, existsSync } from 'fs';

// Load selector convention from config
const configPath = new URL('./e2e.config.json', import.meta.url).pathname;
const config = existsSync(configPath)
  ? JSON.parse(readFileSync(configPath, 'utf-8'))
  : {};
const attr = config.selectors?.convention || 'data-testid';

/** Helper: build a selector string from a testid value */
export function tid(id: string): string {
  return `[${attr}="${id}"]`;
}

/**
 * Core selectors required by gate tests.
 * Extend this object for additional screens/components.
 */
export const SELECTORS = {
  // --- Auth / Login ---
  loginPage: tid('login-page'),
  loginEmailInput: tid('login-email-input'),
  loginSubmitButton: tid('login-submit'),

  // --- Protected / Dashboard ---
  dashboardPage: tid('dashboard-page'),
  dashboardNav: tid('dashboard-nav'),
  dashboardHeading: tid('dashboard-heading'),
  dashboardAnchor: tid('dashboard-anchor'),

  // --- Common Layout ---
  appRoot: tid('app-root'),
  mainContent: tid('main-content'),
  navBar: tid('nav-bar'),
  errorBoundary: tid('error-boundary'),
} as const;

export type SelectorKey = keyof typeof SELECTORS;

/**
 * Get all selectors as a flat list (for auditing).
 */
export function allSelectors(): Array<{ key: string; selector: string }> {
  return Object.entries(SELECTORS).map(([key, selector]) => ({
    key,
    selector,
  }));
}
